### ISSUE TITLE
推送地址该如何设定

### ISSUE THREAD

**Issue by chenlize96** [Weltolk/weltolk_sign_qq#4]
进入 每日签到qq推送 -> 增加推送目标 
发现 使用的推送地址 无法选定也无法输入， 该如何设定这个，谢谢。

**Comment by Weltolk** [comment]
> 进入 每日签到qq推送 -> 增加推送目标 发现 使用的推送地址 无法选定也无法输入， 该如何设定这个，谢谢。

需要先在 每日签到qq推送 -> 推送地址 里,添加推送地址,这个按钮在上方菜单栏的位置

![image](https://github.com/Weltolk/weltolk_sign_qq/assets/40228052/a17229b4-4aed-4cb8-8b38-0bd9a9604be1)
